backend:
  name: github
  repo: Samu-cdm/site_outlet
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "produtos"
    create: true
    extension: json
    fields:
      - {label: "Nome", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Preço", name: "price", widget: "string"}
      - {label: "Foto", name: "image", widget: "image"}
