backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "produtos" # Pasta onde os arquivos vao cair
    create: true
    extension: json # SALVAR EM JSON PARA O SITE LER FACIL
    fields:
      - {label: "Nome", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Preço", name: "price", widget: "string"}
      - {label: "Foto", name: "image", widget: "image"}
