backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nome do Produto", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Preço", name: "price", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}